name: CI WORKFLOW

on: 
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  initial_setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.19'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  export_raw_data:
    runs-on: ubuntu-latest
    needs: initial_setup

    steps:
    - name: export_data
      env:
        dbname: ${{ secrets.DBNAME }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
      run: |
        python src/connections/postgres_export.py

    - name: test_export_data
      run: |
        pytest test_postgres_export.py

